### ISSUE TITLE
ChatCraft 'crashes' when accessing Shared Chats or Searchbar

### ISSUE THREAD

**Issue by rjwignar** [tarasglek/chatcraft.org#446]
@humphd @Amnish04 The last time this happened, did it also affect Shared Chats and the Searchbar?
I'm also seeing issues accessing Shared Chats:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/d11c8551-2771-4df1-a0f4-3826ce10501d)

and when using the search bar:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/a0411680-40d5-43cd-84e5-69bcd95ac948)

_Originally posted by @rjwignar in https://github.com/tarasglek/chatcraft.org/issues/442#issuecomment-1940281321_

**Comment by humphd** [comment]
What's in your console logs when this crash happens?

**Comment by rjwignar** [comment]
@humphd  
## Shared Chats

### When access from Shared Chats Tab
With Shared Chats (accessed from my Shared Chats tab), I get this error in my Dev Tools console:
```console
{
    "status": 404,
    "statusText": "Not Found",
    "internal": true,
    "data": "Error: No route matches URL \"/api/share/rjwignar/bRw2wYMh5UvOc5J7UDen_\"",
    "error": {}
}
```

When I access the same chat via a [share link](https://chatcraft.org/c/rjwignar/sXIHj-eLoiam6NEFM2rOB), I get this error:
```console
{
    "_e": {},
    "name": "DataError",
    "message": "Failed to execute 'get' on 'IDBObjectStore': The parameter is not a valid key.\n DataError: Failed to execute 'get' on 'IDBObjectStore': The parameter is not a valid key.",
    "inner": {
        "stack": "Error: Failed to execute 'get' on 'IDBObjectStore': The parameter is not a valid key.\n    at https://chatcraft.org/assets/index-sGYt3Ste.js:425:30652\n    at Kq (https://chatcraft.org/assets/index-sGYt3Ste.js:424:3694)\n    at new Be (https://chatcraft.org/assets/index-sGYt3Ste.js:424:3190)\n    at Object.get (https://chatcraft.org/assets/index-sGYt3Ste.js:425:30599)\n    at c.<computed> [as get] (https://chatcraft.org/assets/index-sGYt3Ste.js:425:51078)\n    at https://chatcraft.org/assets/index-sGYt3Ste.js:425:6066\n    at s (https://chatcraft.org/assets/index-sGYt3Ste.js:425:5768)\n    at https://chatcraft.org/assets/index-sGYt3Ste.js:425:4706\n    at m0 (https://chatcraft.org/assets/index-sGYt3Ste.js:425:3473)\n    at qc (https://chatcraft.org/assets/index-sGYt3Ste.js:425:2313)"
    }
}
```


## Search Bar
When I type a keyword into the search bar and press <Enter>, this error shows up in the Dev Tools console:
```console
{
    "_e": {},
    "name": "SchemaError",
    "message": "KeyPath [searchText+messages] on object store chats is not indexed",
    "inner": null
}
```

**Comment by humphd** [comment]
The first 404 is odd, since that object exists in the R2 bucket:

```
bRw2wYMh5UvOc5J7UDen_ text/html 99.66 KB February 7, 2024 8:32
```

For the second, this also exists in the bucket, but maybe not in your indexeddb for some reason?  You should look for that key:

```
sXIHj-eLoiam6NEFM2rOB text/html 468.69 KB February 9, 2024 4:3
```

These two errors imply that we're somehow requesting the wrong key at the API level in the router (client side) or CloudFlare function?

The search error is different.  It likely means we are trying to search on some field that is now not being indexed, maybe due to the data migration we did for the Image Preview change.  We need to research this more.

**Comment by humphd** [comment]
This share fails for me:

https://chatcraft.org/c/tarasglek/xp5A6rszHiqroXp22E6Ap

Loading that URL returns HTML.  I can't easily reproduce this locally, but it would be good to figure this out.

**Comment by Amnish04** [comment]
@Rachit1313 @humphd Are we moving this to 1.4?

**Comment by humphd** [comment]
I have a PR up for it, let's do for 1.3
